apiVersion: v1
kind: ConfigMap
metadata:
  name: room-booking-config
  namespace: room-booking
data:
  # Nezauta konfigurace — zadne citlive udaje zde
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:postgresql://postgres-service:5432/roombooking"
  DB_USERNAME: "roombooking"
