apiVersion: v1
kind: Secret
metadata:
  name: room-booking-secret
  namespace: room-booking
type: Opaque
data:
  # Hodnoty jsou base64
  # Vygenerovat: echo -n 'tveHeslo' | base64
  db-password: cm9vbWJvb2tpbmc=           # "roombooking"
